### PR TITLE
Support postcss-apply

### LINKED ISSUE #4: Plugin breaks when applied to a file containing a css property set
The [@apply spec](https://tabatkins.github.io/specs/css-apply-rule/) defines 'css property sets' like this:

``` css
.warning {
  --toolbar-title-theme: {
    color: red;
    font-weight: bold;
  };
}
```

These are currently in production use on sites using Polymer.

However when trying to process css with this plugin I get an error like:

```
Error: Expected pseudo-class or pseudo-element
    at new error ({app}/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error ({app}/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo ({app}/node_modules/postcss-selector-parser/dist/parser.js:292:25)
    at Parser.parse ({app}/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop ({app}/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser ({app}/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process ({app}/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at {app}/node_modules/postcss-pseudo-class-any-link/index.js:48:7
    at {app}/node_modules/postcss/lib/container.js:118:28
    at {app}/node_modules/postcss/lib/container.js:81:26
    at Rule.each ({app}/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk ({app}/node_modules/postcss/lib/container.js:80:21)
    at {app}/node_modules/postcss/lib/container.js:83:32
    at Root.each ({app}/node_modules/postcss/lib/container.js:68:22)
    at Root.walk ({app}/node_modules/postcss/lib/container.js:80:21)
    at Root.walkRules ({app}/node_modules/postcss/lib/container.js:116:25)
```

This bug is exclusive to any-link. I have postcss-selector-matches, postcss-selector-not, and postcss-nesting all present and none of them have an issue with the syntax.

### PR DESCRIPTION
**Pull request by texastoland**
@dantman Fixes #4. CC @MoOx in case cssnext needs updated. FYI @spicydonuts.

### CODE REVIEW

**Comment by MoOx** [comment]
If this is a patch and is delivered as a patch (following semver spec), cssnext will get the patch automatically.

**Comment by texastoland** [comment]
I assumed so 🙏

**Comment by texastoland** [comment]
Working in my build so far.

**Comment by texastoland** [comment]
Thanks! Could it be tagged as a patch to propagate to cssnext?

**Comment by onigoetz** [comment]
Hi @jonathantneal will this get tagged soon ? I'm trying to use `@apply` in my project, but this issue prevents me from doing so

**Comment by entozoon** [comment]
+1
"Expected pseudo-class.." when attemping to use the documented @apply function by having code such as:

```
:root {
    --foo: {
        display: block
    };
}
```

**Pull request merged**
